In [3]:
import numpy as np

N = 4
Move_Reward = -1
Value = np.zeros((N, N))
Gamma = 1
Threshold = 10**-4 
#Initializations

In [4]:
spaces = np.array([[-1, 0], [1, 0], [0, -1], [0, 1]])  # Movement directions (up, down, left, right)

In [5]:
def get_next(i, j):
    output = []
    for space in spaces:
        temp = [i + space[0], j + space[1]]  # Calculate next potential state
        # Check if the next state is within grid bounds
        if 0 <= temp[0] < N and 0 <= temp[1] < N:
            output.append(temp)
    return output

In this approach, I only consider the next valid states when applying the Bellman equation. This avoids giving states near the boundaries an unfair disadvantage. Since we assume equal probability for all possible moves, allowing out-of-bounds moves to contribute to the expected value would artificially lower the value of edge states (due to missing contributions from invalid moves). By restricting the calculation to only valid next states, we ensure that all states are treated fairly without unintended value loss.

In [6]:
def bellman(i, j):
    options = get_next(i, j)  # Get possible next states
    output = 0
    for option in options:
        if option == [N-1, N-1]:  # Skip the terminal state (bottom-right corner)
            continue
            # Terminal state has reward 0 and value 0 (no update needed)
        else:
            # Calculate value based on valid moves (average of all possible next states)
            output += (Move_Reward + Gamma * Value[option[0], option[1]]) / len(options)
    return output

In [7]:
# Initialization of temp to a large value for the loop condition
temp = float('inf')
while temp > Threshold:  # Continue until convergence
    maxupdate = 0  # Track the maximum value update for convergence
    for i in range(N):  # Loop over each state in the grid
        for j in range(N):
            if [i, j] == [N-1, N-1]:  # Skip the terminal state (bottom-right corner)
                continue
            current_value = Value[i, j]  # Store the current value of the state
            new_value = bellman(i, j)  # Get the new value from Bellman's equation
            maxupdate = max(maxupdate, abs(current_value - new_value))  # Track max change
            Value[i, j] = new_value  # Update the value grid with the new value for the state
    temp = maxupdate  # Update temp to the maximum change to check for convergence

print(Value)

[[-43.56965659 -42.56974832 -40.21275171 -37.78431951]
 [-42.56974832 -40.92700588 -37.28433855 -33.35595231]
 [-40.21275171 -37.28433855 -30.64176871 -21.99924034]
 [-37.78431951 -33.35595231 -21.99924034   0.        ]]
